name: Create Release on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  createRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install PyGithub

      - name: Create Release
        if: startsWith(github.base_ref, 'rc_') || endsWith(github.base_ref, '.x') || github.base_ref == 'develop'
        run: |
          BASE_BRANCH=${{ github.base_ref }}
          GIT_REPO=${{ github.repository }}
          GIT_TOKEN=${{ secrets.GITHUB_TOKEN }}
          LATEST_COMMIT=${{ github.event.pull_request.head.sha }}
          SOURCE_BRANCH=${{ github.head_ref }}
          python .github/scripts/create_release_notes_from_pr.py  $BASE_BRANCH $GIT_REPO $GIT_TOKEN $LATEST_COMMIT
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_TOKEN: ${{ secrets.MH_PUSH }}

