name: Check PR Description

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_pr_description:
    runs-on: ubuntu-latest

    if: startsWith(github.base_ref, 'rc_') || endsWith(github.base_ref, '.x') || github.base_ref == 'develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR title for Build
        if: startsWith(github.event.pull_request.title, 'Build')
        run: |
          echo "PR title starts with 'Build'. Merging without further checks."
          # Merge the pull request using GitHub API or any other method you prefer
          exit 0

      - name: Check PR description
        run: |

          title=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
          echo $GITHUB_EVENT_PATH
          echo $title
          title_pattern="Build.*"
          if [[ "$title" =~ $title_pattern ]]; then
            echo "Title has 'Build', skipping description check."
            exit 0
          fi
          # Extract PR description
          description=$(jq --raw-output .pull_request.body "$GITHUB_EVENT_PATH")
          echo $description

          echo $HELLO

          # Define compulsory and optional patterns
          compulsory_pattern="Title:.*Description:.*Jira:.*Test Report:.*"
          optional_pattern="(Deprecated Features:|Dependencies:|Limitations:).*"

          # Check PR description
          if [[ "$description" =~ $compulsory_pattern ]]; then
            echo "PR description is valid."
            
            if [[ "$description" =~ Deprecated\ Features || "$description" =~ Dependencies || "$description" =~ Limitations ]]; then
              echo "PR description includes optional information. Approval granted."
            else
              echo "PR description does not include optional information. Additional approval may be required."
            fi
          elif [[ "$description" =~ $optional_pattern ]]; then
            echo "PR description does not include compulsory information, but includes optional information. Approval granted."
          else
            echo "PR description is not valid. Please ensure it follows the required format."
            exit 1
          fi
