name: Python Workflow

on:
  pull_request:
    branches:
      - mj-5.31.x

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MH_PUSH }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install GitPython
      - name: Set git identity
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Run Python script
        run: |
            git checkout main
            date > generated.txt
            git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "generated"
            git push
